<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($name="")
    {
        $query = $this->createQueryBuilder("this")
                      ->where("this.name = :name")
                      ->setParameter("name", $name)
                      ->getQuery();

        try  {return $query->getArrayResult();}
        catch (ORMException $e) {return null;}
    
    }
}
